=== izzyreal/mpc/resources/midicontrolpresets/vmpc2000xl_midi_control_preset.schema.v3.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://izmar.nl/vmpc2000xl_midi_control_preset.schema.v3.json",
  "title": "MIDI Control Preset",
  "type": "object",
  "required": [
    "version",
    "name",
    "autoLoadMode",
    "bindings"
  ],
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 0,
      "maximum": 4503599627370496,
      "default": 0,
      "description": "Integer between 0 and 2^52 inclusive."
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 16,
      "pattern": "^[A-Za-z0-9 !#\\$%&'\\(\\)\\-@_{}]+$",
      "description": "Preset name: 1 to 16 characters using allowed characters [A-Za-z0-9 !#$%&'()-@_{}]. Required in every preset."
    },
    "midiControllerDeviceName": {
      "type": "string",
      "maxLength": 255,
      "pattern": "^[a-zA-Z0-9 _\\-\\.\\(\\)\\/\\,;]*$",
      "description": "Optional name of the MIDI controller device. Can be empty or up to 255 characters using allowed characters [a-zA-Z0-9 _-./(),;]."
    },
    "autoLoadMode": {
      "type": "string",
      "enum": [
        "No",
        "Ask",
        "Yes"
      ],
      "default": "No",
      "description": "Controls automatic loading of the preset. 'No': never auto-load. 'Yes': auto-load if a MIDI controller with `midiControllerDeviceName` is connected. 'Ask': prompt the user to load if the controller is connected."
    },
    "bindings": {
      "type": "array",
      "minItems": 0,
      "maxItems": 65536,
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/binding"
      },
      "description": "Array of MIDI control bindings."
    }
  },
  "$defs": {
    "binding": {
      "type": "object",
      "required": [
        "target",
        "messageType",
        "midiNumber",
        "midiChannelIndex"
      ],
      "additionalProperties": false,
      "properties": {
        "target": {
          "type": "string",
          "maxLength": 64,
          "pattern": "^[a-z0-9_\\-#:]+$",
          "enum": [
            "hardware:pad-1-or-ab",
            "hardware:pad-2-or-cd",
            "hardware:pad-3-or-ef",
            "hardware:pad-4-or-gh",
            "hardware:pad-5-or-ij",
            "hardware:pad-6-or-kl",
            "hardware:pad-7-or-mn",
            "hardware:pad-8-or-op",
            "hardware:pad-9-or-qr",
            "hardware:pad-10-or-st",
            "hardware:pad-11-or-uv",
            "hardware:pad-12-or-wx",
            "hardware:pad-13-or-yz",
            "hardware:pad-14-or-ampersand-octothorpe",
            "hardware:pad-15-or-hyphen-exclamation-mark",
            "hardware:pad-16-or-parentheses",
            "hardware:data-wheel:negative",
            "hardware:data-wheel:positive",
            "hardware:data-wheel",
            "hardware:slider",
            "hardware:rec-gain-pot",
            "hardware:main-volume-pot",
            "hardware:rec",
            "hardware:overdub",
            "hardware:stop",
            "hardware:play",
            "hardware:play-start",
            "hardware:cursor-left-or-digit",
            "hardware:cursor-right-or-digit",
            "hardware:cursor-up",
            "hardware:cursor-down",
            "hardware:main-screen",
            "hardware:prev-step-or-event",
            "hardware:next-step-or-event",
            "hardware:go-to",
            "hardware:prev-bar-or-start",
            "hardware:next-bar-or-end",
            "hardware:tap-or-note-repeat",
            "hardware:next-seq",
            "hardware:track-mute",
            "hardware:open-window",
            "hardware:full-level-or-case-switch",
            "hardware:sixteen-levels-or-space",
            "hardware:f1",
            "hardware:f2",
            "hardware:f3",
            "hardware:f4",
            "hardware:f5",
            "hardware:f6",
            "hardware:shift",
            "hardware:enter-or-save",
            "hardware:undo-seq",
            "hardware:erase",
            "hardware:after-or-assign",
            "hardware:bank-a",
            "hardware:bank-b",
            "hardware:bank-c",
            "hardware:bank-d",
            "hardware:0-or-vmpc",
            "hardware:1-or-song",
            "hardware:2-or-misc",
            "hardware:3-or-load",
            "hardware:4-or-sample",
            "hardware:5-or-trim",
            "hardware:6-or-program",
            "hardware:7-or-mixer",
            "hardware:8-or-other",
            "hardware:9-or-midi-sync"
          ]
        },
        "messageType": {
          "type": "string",
          "enum": [
            "controller",
            "note"
          ]
        },
        "midiNumber": {
          "type": "integer",
          "minimum": -1,
          "maximum": 127
        },
        "midiValue": {
          "type": "integer",
          "minimum": 1,
          "maximum": 127,
          "description": "Threshold for button targets."
        },
        "midiChannelIndex": {
          "type": "integer",
          "minimum": -1,
          "maximum": 15,
          "description": "Zero-based indexing (0â€“15), or -1 for 'all'."
        },
        "encoderMode": {
          "type": "string",
          "enum": [
            "relative_stateless",
            "relative_stateful"
          ]
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "messageType": {
                "const": "controller"
              }
            },
            "required": [
              "messageType"
            ]
          },
          "then": {
            "if": {
              "properties": {
                "target": {
                  "enum": [
                    "hardware:cursor-left-or-digit",
                    "hardware:cursor-right-or-digit",
                    "hardware:cursor-up",
                    "hardware:cursor-down",
                    "hardware:rec",
                    "hardware:overdub",
                    "hardware:stop",
                    "hardware:play",
                    "hardware:play-start",
                    "hardware:main-screen",
                    "hardware:prev-step-or-event",
                    "hardware:next-step-or-event",
                    "hardware:go-to",
                    "hardware:prev-bar-or-start",
                    "hardware:next-bar-or-end",
                    "hardware:tap-or-note-repeat",
                    "hardware:next-seq",
                    "hardware:track-mute",
                    "hardware:open-window",
                    "hardware:full-level-or-case-switch",
                    "hardware:sixteen-levels-or-space",
                    "hardware:f1",
                    "hardware:f2",
                    "hardware:f3",
                    "hardware:f4",
                    "hardware:f5",
                    "hardware:f6",
                    "hardware:shift",
                    "hardware:enter-or-save",
                    "hardware:undo-seq",
                    "hardware:erase",
                    "hardware:after-or-assign",
                    "hardware:bank-a",
                    "hardware:bank-b",
                    "hardware:bank-c",
                    "hardware:bank-d",
                    "hardware:0-or-vmpc",
                    "hardware:1-or-song",
                    "hardware:2-or-misc",
                    "hardware:3-or-load",
                    "hardware:4-or-sample",
                    "hardware:5-or-trim",
                    "hardware:6-or-program",
                    "hardware:7-or-mixer",
                    "hardware:8-or-other",
                    "hardware:9-or-midi-sync",
                    "hardware:data-wheel:negative",
                    "hardware:data-wheel:positive"
                  ]
                }
              },
              "required": [
                "target"
              ]
            },
            "then": {
              "required": [
                "midiValue"
              ]
            },
            "else": {
              "not": {
                "required": [
                  "midiValue"
                ]
              }
            }
          },
          "else": {
            "not": {
              "required": [
                "midiValue"
              ]
            }
          }
        },
        {
          "if": {
            "properties": {
              "target": {
                "const": "hardware:data-wheel"
              }
            },
            "required": [
              "target"
            ]
          },
          "then": {
            "required": [
              "encoderMode"
            ],
            "not": {
              "required": [
                "midiValue"
              ]
            }
          },
          "else": {
            "properties": {
              "encoderMode": false
            }
          }
        }
      ],
      "default": {
        "messageType": "controller",
        "midiNumber": -1,
        "midiValue": 64,
        "midiChannelIndex": -1,
        "encoderMode": "relative_stateless"
      }
    }
  }
}

=== izzyreal/mpc/resources/midicontrolpresets/MPD218.json
{
    "autoLoadMode": "Ask",
    "bindings": [
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 36,
            "target": "hardware:pad-1-or-ab"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 37,
            "target": "hardware:pad-2-or-cd"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 38,
            "target": "hardware:pad-3-or-ef"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 39,
            "target": "hardware:pad-4-or-gh"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 40,
            "target": "hardware:pad-5-or-ij"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 41,
            "target": "hardware:pad-6-or-kl"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 42,
            "target": "hardware:pad-7-or-mn"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 43,
            "target": "hardware:pad-8-or-op"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 44,
            "target": "hardware:pad-9-or-qr"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 45,
            "target": "hardware:pad-10-or-st"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 46,
            "target": "hardware:pad-11-or-uv"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 47,
            "target": "hardware:pad-12-or-wx"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 48,
            "target": "hardware:pad-13-or-yz"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 49,
            "target": "hardware:pad-14-or-ampersand-octothorpe"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 50,
            "target": "hardware:pad-15-or-hyphen-exclamation-mark"
        },
        {
            "messageType": "note",
            "midiChannelIndex": -1,
            "midiNumber": 51,
            "target": "hardware:pad-16-or-parentheses"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "target": "hardware:data-wheel:negative"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "target": "hardware:data-wheel:positive"
        },
        {
            "encoderMode": "relative_stateless",
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": 3,
            "target": "hardware:data-wheel"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": 9,
            "target": "hardware:slider"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": 12,
            "target": "hardware:rec-gain-pot"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": 13,
            "target": "hardware:main-volume-pot"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:rec"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:overdub"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:stop"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:play"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:play-start"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:cursor-left-or-digit"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:cursor-right-or-digit"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:cursor-up"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:cursor-down"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:main-screen"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:prev-step-or-event"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:next-step-or-event"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:go-to"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:prev-bar-or-start"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:next-bar-or-end"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:tap-or-note-repeat"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:next-seq"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:track-mute"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:open-window"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:full-level-or-case-switch"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:sixteen-levels-or-space"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:f1"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:f2"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:f3"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:f4"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:f5"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:f6"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:shift"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:enter-or-save"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
            "midiNumber": -1,
            "midiValue": 64,
            "target": "hardware:undo-seq"
        },
        {
            "messageType": "controller",
            "midiChannelIndex": -1,
